; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Testing"
#define MyAppVersion "1.0"
#define MyAppPublisher "Mali Software"
#define MyAppExeName "Testing.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7B5C9A12-C0A7-4814-8C36-EAD83B50F525}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=mysetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\оо.01\Testing\Testing\bin\Release\Testing.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\Microsoft.Bcl.AsyncInterfaces.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\Newtonsoft.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Buffers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Numerics.Vectors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Runtime.CompilerServices.Unsafe.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Text.Encodings.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Text.Encodings.Web.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Text.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Text.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.Threading.Tasks.Extensions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.ValueTuple.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\System.ValueTuple.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\bin\Release\Testing.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\Users.mdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\оо.01\Testing\Testing\Users_log.ldf"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

